[package]
name = "evolution-island"
version = "0.1.1"
authors = []
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", rev = "2509c43", features = ["vulkan", "gltf"]}
rand = "0.6.5"
log = "0.4.6"
smart-default = "0.5.2"
serde = "1.0.90"
thread_profiler = "0.3.0"

# TODO: update dependencies for Amethyst newest version
#amethyst_test = "0.2.0"
#amethyst-imgui = "0.3.0"
#amethyst-inspector = { git = "https://github.com/awpteamoose/amethyst-inspector.git"}

[features]
profiler = [
    "thread_profiler/thread_profiler",
    "amethyst/profiler"
]


